// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB365jO2-PVfqKBl5dnKaVl3dTLVDJK1Qs',
    appId: '1:359041787967:web:505195a0b1176f445af08a',
    messagingSenderId: '359041787967',
    projectId: 'gstore-eb755',
    authDomain: 'gstore-eb755.firebaseapp.com',
    storageBucket: 'gstore-eb755.appspot.com',
    measurementId: 'G-757G0ZMS5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLEyMtb_Y3f7SqD7Q6ZsIK5DWojEKm61k',
    appId: '1:359041787967:android:521a6febef86065f5af08a',
    messagingSenderId: '359041787967',
    projectId: 'gstore-eb755',
    storageBucket: 'gstore-eb755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUUnk8u3tU-UbKjZ_9IPRir-8mO7YwAw',
    appId: '1:359041787967:ios:7e22c454f033f7155af08a',
    messagingSenderId: '359041787967',
    projectId: 'gstore-eb755',
    storageBucket: 'gstore-eb755.appspot.com',
    androidClientId: '359041787967-2j5s8ob9s9rlvi7ca65vs1htssl1r4fe.apps.googleusercontent.com',
    iosClientId: '359041787967-frsdu04b6j34p5ro9e80o5muh8ocuu69.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}